name: Extractor_Rapido

on:
  schedule:
    - cron: '0 9 * * *' # Ejecuta todos los días a las 09:00 UTC
  workflow_dispatch: # Botón para ejecutar manual

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar Libreria Correcta
        run: pip install youtube-transcript-api==1.2.3

      - name: Ejecutar Script
        # Ejecutamos el archivo que se llama main.py
        run: python main.py

      - name: Subir Resultado
        uses: actions/upload-artifact@v4
        with:
          name: MiTranscripcion
          path: resultado.txt