name: Bot de Noticias Youtube

on:
  schedule:
    - cron: '*/30 * * * *'  # Se ejecuta cada 30 minutos
  workflow_dispatch:        # Bot√≥n manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar Dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Correr Bot
        env:
          # Aqu√≠ se pasan las llaves de la caja fuerte al c√≥digo
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # üëá ¬°ESTA ES LA L√çNEA QUE FALTABA! üëá
          SUPADATA_API_KEY: ${{ secrets.SUPADATA_API_KEY }}
        run: python main.py