name: Bot de Noticias Youtube

on:
  schedule:
    - cron: '*/30 * * * *'  # Se ejecuta cada 30 minutos
  workflow_dispatch:        # Permite ejecutarlo manualmente con el botón

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Solo necesitamos Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # VITAL: Instalar FFmpeg (Sin esto, Whisper falla)
      - name: Instalar FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Instalar lo que pusimos en requirements.txt
      - name: Instalar Librerías
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Correr Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py