name: Bot de Noticias Youtube

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Instalación desde la Fuente (Nuclear)
        run: |
          pip install --upgrade pip
          # 1. Instalamos las librerías normales
          pip install google-generativeai sqlalchemy psycopg2-binary google-api-python-client
          
          # 2. AQUÍ ESTÁ EL TRUCO:
          # No usamos el nombre, usamos la dirección exacta del código fuente oficial.
          # Esto evita que descargue la versión "1.2.3" falsa.
          pip install git+https://github.com/jdepoix/youtube-transcript-api.git
          
      - name: Correr Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py