name: Bot de Noticias Youtube

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Instalación Manual (Bypassing PIP)
        run: |
          pip install --upgrade pip
          # 1. Instalamos las demás librerías
          pip install -r requirements.txt
          
          # 2. DESCARGAMOS EL CÓDIGO FUENTE DE LA LIBRERÍA MANUALMENTE
          git clone https://github.com/jdepoix/youtube-transcript-api.git temp_library
          
          # 3. MOVEMOS LA CARPETA INTERNA A LA RAÍZ (Aquí está el truco)
          mv temp_library/youtube_transcript_api .
          
          # 4. Borramos lo que sobra
          rm -rf temp_library
          
          # Confirmamos que la carpeta está ahí
          ls -F
          
      - name: Correr Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py