name: Bot de Noticias Youtube

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Instalación Local (El Truco Definitivo)
        run: |
          pip install --upgrade pip
          
          # 1. Instalamos las dependencias normales
          pip install -r requirements.txt
          
          # 2. INSTALAMOS LA LIBRERÍA EN LA CARPETA ACTUAL (Target)
          # Esto crea una carpeta 'youtube_transcript_api' justo al lado de main.py
          pip install --target . youtube-transcript-api==0.6.3
          
          # 3. Verificamos que la carpeta existe
          ls -d youtube_transcript_api
          
      - name: Correr Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py