name: Bot de Noticias Youtube

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # NO usamos caché para evitar problemas de versiones viejas
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Instalación Forzada
        run: |
          pip install --upgrade pip
          # Esta línea es la MAGIA: Borra lo viejo e instala lo nuevo a la fuerza
          pip install --force-reinstall -v "youtube-transcript-api>=0.6.2" -r requirements.txt
          
      - name: Correr Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py