name: Bot de Noticias Youtube

on:
  schedule:
    - cron: '*/30 * * * *'  # Se ejecuta cada 30 minutos
  workflow_dispatch:        # Te deja probarlo manual con el botón

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # NOTA: Ya no instalamos FFmpeg ni Tor porque solo procesamos texto.
      
      - name: Instalar Librerías
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Correr Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py