name: Bot de Noticias Youtube

on:
  schedule:
    - cron: '*/30 * * * *' # Ejecutar cada 30 min
  workflow_dispatch:      # BotÃ³n manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar requisitos
        run: pip install --force-reinstall -v "youtube-transcript-api>=0.6.1" -r requirements.txt
      - name: Correr Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py